### ISSUE TITLE
TS : Permettre à l'API de renvoyer des observables Rxjs à la place des promesses

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#112]
Pour utiliser TopModel avec Angular

**Comment by Jerom138** [comment]
Comme vu ensemble, en fait, avec Angular, il serait préférable d'utiliser le HttpClient, et pour cela d'être capable de gérer l'injection de dépendance, et donc une classe de service avec une méthode par endpoint.

Par ailleurs, un point d'entrée pour l'utilisateur est nécessaire pour permettre de préciser le chemin relatif des endpoints (par exemple "/api/v1"... (_EnvService_ dans l'exemple ci-après)

**Exemple de service simple :** 

import { Injectable } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { EnvService } from "src/app/services/env.service";
import { Observable } from "rxjs";
import { UtilisateurConsultDto } from "@/appgenerated/model/utilisateur/utilisateur-consult-dto";

@Injectable({
providedIn: 'root'
})
export class UtilisateurService {
    constructor(private http: HttpClient, private env: EnvService) {}

    getUtilisateurConnecte(): Observable<UtilisateurConsultDto> {
        return this.http.get<UtilisateurConsultDto>(`${this.env.apiRootUrl}/utilisateur/connecte`);
    }
}

**Comment by Jerom138** [comment]
**Exemple avec PUT, DELETE, POST :** 

import { Injectable } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { Observable } from "rxjs";
import { EnvService } from "src/app/services/env.service";
import { AemcSurveillanceAudit } from "src/app/model/aemcSurveillanceAudit";
import { AEMC } from "src/app/model/aemc";

@Injectable({
  providedIn: 'root'
})
export class AemcSurveillanceAuditService {
  constructor(private http: HttpClient, private env: EnvService) {}  
  
  createSurveillanceAudit(aemcId: number, audit: AemcSurveillanceAudit): Observable<AEMC> {
    return this.http.post<AEMC>(`${this.env.apiRootUrl}/aemc/audit/surveillance/${aemcId}`, audit);
  }

  updateSurveillanceAudit(audit: AemcSurveillanceAudit): Observable<AemcSurveillanceAudit> {
    return this.http.put<AemcSurveillanceAudit>(`${this.env.apiRootUrl}/aemc/audit/surveillance`, audit);
  }

  deleteSurveillanceAudit(auditId: number) {
    return this.http.delete(`${this.env.apiRootUrl}/aemc/audit/surveillance/${auditId}`);
  }
}
