### ISSUE TITLE
JS : Placer les API dans un répertoire correspondant au module

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#17]
Actuellement le fichier est placé en fonction de sa position par rapport à la racine du projet topmodel

**Comment by JabX** [comment]
Il faudrait que ça soit paramétrable (utiliser ou non le module)
Et il faudrait faire la même chose côté C# où on utilise la même convention
Côté spring ça utilise déjà le module (mais ce n'a pas vocation à être paramétrable)
