### ISSUE TITLE
[i18n] Gérer les traductions de listes de référence en SQL

### ISSUE THREAD

**Issue by JabX** [klee-contrib/topmodel#174]
La PR #173 traite le sujet général et implémente la gestion pour le JS et JPA, mais il manque encore l'équivalence en SQL et en C# (au moins pour les libellés de listes de référence, vu qu'on ne génère pas les autres libellés avec ces générateurs)

**Comment by gideruette** [comment]
Implémentation SQL : 
- Ajouter la propriété `resourceTableName`
- Générer le script de création de la table de traduction avec :
  - resource_key : correspond à la clé de traduction
  - locale : correspond à la langue traduite
  - label : traduction
  - La pk porte sur les colonnes (resource_key , locale)
- Pour les listes de références, ajouter la FK vers la table de traduction, mais uniquement sur la colonne `resource_key `
- Ajouter les insertions de traductions, des propriétés et des libellés de listes de références selon le paramétrage
