### ISSUE TITLE
Message d'erreur si doublon de déclaration de route + method dans les endpoints

### ISSUE THREAD

**Issue by vit-Cos** [klee-contrib/topmodel#177]
Qu'il y ait un message d'erreur spécifique lors de l'utilisation de la commande 'modgen' quand topModel constate qu'il y a 2 endpoints qui ont la même route et même méthode.

Exemple : 
![image](https://user-images.githubusercontent.com/109680690/209163291-a183e8fc-4207-4053-8a31-4d072b8e6109.png)

(Actuellement cela ne dit rien alors que ça pourrait nous faire gagner du temps et serait une sorte de tests de non régression supplémentaire sur les appli utilisant topModel)

**Comment by JabX** [comment]
Même route (avec préfixe) + même méthode pour 2 endpoints dans des fichiers qui ont au moins un tag en commun (si c'est le même fichier évidemment ça marche aussi) = erreur.

On n'attrapera pas les doublons avec des tags différents mais c'est voulu, dans le sens où si les tags sont différents c'est probablement parce que ce n'est pas la même API qui est générée, et donc qu'on pourrait tout à fait avoir deux routes/méthodes identiques dans ce cas sans que ça ne pose problème. Si jamais c'était la même API, ce n'est déjà pas une bonne pratique de n'avoir aucun tag en commun, et au final tant pis. En revanche, si le tag est le même, ça veut forcément dire que c'est généré pour la même API et qu'il est impossible d'avoir un doublon.

Il faut bien inclure le fait en revanche que la route n'est pas la même s'il y a un paramètre de route d'un type différent à l'intérieur.  On comparera les types Java et C# pour confirmer qu'ils sont différents (le domaine ne serait pas malheureusement pas suffisant...).

**Comment by etienne582** [comment]
UPVOTE

**Comment by JabX** [comment]
Le contrôle à mettre en place est beaucoup trop compliqué pour la valeur qu'il apporte, désolé :(
