### ISSUE TITLE
[Core] Dans un domain, pouvoir définir un domain à utiliser dans le cas liste

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#179]
Pour remplacer la propriété `asListWithDomain`, ajouter sur le domain la propriété `listDomain` qui sera utilisée pour :
- Le domaine dans le cas oneToMany
- Le domaine dans le cas manyToOne
- Remplacer le asListWithDomain par asList: true

**Comment by JabX** [comment]
La PR validée ne gère que les alias asList, les associations seront traitées dans une PR suivante
