### ISSUE TITLE
[modgen] Pouvoir décider du regroupement par module/sous-module

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#216]
Dans les propriétés qui permettent d'ajouter le mot clé `module`, accepeter les syntaxes suivantes :
- `{module[0]}`
- `{module[0..1]}`
- `{module[1..]}`
- `{module[0..2]}`
- `{module[0..^1]}`

Même syntaxe qu'en C#.

**Comment by JabX** [comment]
Après avoir pas mal passé de temps sur le sujet avec #225, je fais le constat suivant : 

## Module racine

On n'utilise le module racine que pour la génération des traductions (JS, JPA et TranslationOut). Je dirais que la valeur de regrouper autrement est assez faible, à la limite je préfèrerai sortir qu'un seul fichier par langue plutôt que de le rediviser en sous-modules. C'est fait en dur et ce n'est pas paramétrable (on dit juste aux générateurs où mettre les fichiers dans un chemin qui ne peut dépendre que de la langue).

Le module racine est aussi utilisé par le générateur JPA pour déterminer si deux classes peuvent avoir une many to many dans les deux sens.

## Module complet 

Tous les autres regroupements utilisent le module complet : 
- Toutes les APIs Client/Server qui ont un regroupement par module imposé avec la fusion de fichiers par `fileName`.
- [JS] Liste de refs (non paramétrable explicitement car on utilise le chemin de génération des classes)
- [C#] Accesseurs de référence (chemin paramétrable par module)
- [C#] Mappers (non paramétrable explicitement car on utilise le chemin de génération des classes)
- [JPA] Mappers (non paramétrable explicitement car on utilise le chemin de génération des classes)

On voit bien le délire : à part le coup des accesseurs de référence (qui n'a aucun intérêt à regrouper autrement puisque ce ne sont pas des classes utilisées directement), tous les autres chemins ne sont pas paramétrables directement et dépendent d'un autre paramètre qui lui doit utiliser le module en entier (classes et endpoints).

On est donc dans tous les cas obligé de complexifier la configuration, y compris pour le cas nominal, afin de pouvoir avoir la main sur un truc qui est totalement acceptable dans sa config par défaut (et encore, déjà il faudrait voir qui utilise des sous-modules, parce que moi non, et je pense qu'aucun projet .NET non plus vu que jusqu'à très récemment ça ne marchait pas vraiment). 

L'idée de base avait l'air fun, mais ça sert franchement à rien :)
