### ISSUE TITLE
JPA - Bug sur les alias d'association

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#22]
Le code généré n'est pas correct sur les alias d'associations, notamment lorsque les alias ont un suffix

**Comment by gideruette** [comment]
Les alias d'association de type ManyToMany et oneToMany doivent générer une liste d'ids (et non juste un id comme actuellement)

**Comment by JabX** [comment]
Il faudrait gérer (enfin) correctement les types d'associations : 
- mettre manyToOne par défaut
- gérer les oneToOne correctement dans les générateurs (clé d'unicité...)
- bloquer les oneToMany/manyToMany dans les générateurs qui ne les gèrent pas (tous sauf JPA, en fait)
- revoir le nom de la propriété d'association pour les oneToMany/manyToMany pour mettre "{classe}s{role}" (on laissera l'utilisateur mettre son rôle au pluriel) au lieu de "{classe}{pk}{role}", et mettre à jour le générateur JPA pour qu'il utilise ce nom là.
