### ISSUE TITLE
[Core] Possibilité de créer des fichiers `[fichier].partial.tmd`

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#221]
Pour étendre des fichiers générés par tmdgen par exemple

**Comment by JabX** [comment]
On ne trouve pas de design satisfaisant pour cette fonctionnalité sans revoir le fonctionnement interne de TopModel, et on n'a pas vraiment de besoin identifié là-dessus pour l'instant (au pire, on peut faire un DTO par dessus la classe générée pour y ajouter les infos en plus si besoin)
