### ISSUE TITLE
[PHP] Implémenter générateur php

### ISSUE THREAD

**Issue by gideruette** [klee-contrib/topmodel#237]
Symfony ou Laravel ou autre ?

**Comment by bdelespierre** [comment]
Laravel est de très loin le plus utilisé dans le monde. C'est aussi un FW beaucoup plus simple et ergonomique que Symfony.

Mais ici <s>c'est Paris</s> c'est la France. Donc ce sera Symfony + Doctrine2 j'imagine 😂
