### ISSUE TITLE
[Extension] Correction du Snippet pour une nouvelle propriété

### ISSUE THREAD

**Issue by etienne582** [klee-contrib/topmodel#296]
![image](https://github.com/klee-contrib/topmodel/assets/15012429/ab629004-0c6b-41c9-bf02-a996c6ae4273)

**Comment by JabX** [comment]
Le snippet est généré par l'extension YAML, ce qui est hors de notre contrôle :(
Tu as qu'à ouvrir un bug chez eux hein :D
