### ISSUE TITLE
[API] ajout d'un apiMode de type Nuxt

### ISSUE THREAD

**Issue by BesnardFlorian** [klee-contrib/topmodel#321]
Est-il possible d'ajouter un nouveau type de framework from 'nuxt' à la manière de ce qui est fait pour angular ?

La différence serait le type attendu en retour des endpoints où il y aurait 'AsyncData<T , Error | null>' au lieu de 'Promise< T >'

**Comment by JabX** [comment]
Si c'est que le type de retour qui change peut être on pourrait juste configurer ça ? Ca serait plus flexible pour la suite si quelqu'un  d'autre veut utiliser un autre framework similaire mais avec un type différent. Le générateur angular génère des clients qui sont trop différents pour être regroupés dans le générateur "normal"...

**Comment by gideruette** [comment]
Nuxt propose aussi une api complète pour faire les fetch, ça vaudrait peut-être le coup de générer qqch qui soit 100% clé en main pour nuxt, plutôt que d'imposer l'implémentation du fetch à raccrocher à Nuxt
