### ISSUE TITLE
[C#] Emplacement Génération Mappers tables de référence

### ISSUE THREAD

**Issue by vit-Cos** [klee-contrib/topmodel#323]
J'ai une table de référence basique, je veux get une partie des champs de cette table donc je créé un DTO avec un mappers from.

Le create de la table n'est pas généré à l'endroit où les références sont générées.

Possible de le générer à cet endroit ? Cela m'oblige de descendre jusqu'au client pour le faire avec l'archi de notre app :(

**Comment by JabX** [comment]
En fait tu voulais le générer à côté du DTO, pas de la table de référence, puisque ce sont les DTOs qui peuvent référencer les tables de référence et non l'inverse.

(Ce fix est un petit breaking change puisque certains mappers vont bouger, mais j'ai testé sur ton projet et les changements sont tout à fait désirables)
