### ISSUE TITLE
[JPA]  Traduction des libellés en bdd, bug

### ISSUE THREAD

**Issue by dchallas** [klee-contrib/topmodel#357]
Suite à l'activation des fonctionnalités de tranductions dans la table resourcesTableName, quelques sujets à corriger/adapter:
1- il manque le point virgule à la fin du create table des tables resourcesTableName
2- dans le fichier initListFile, la clef du libellé est générée avec des doubles quotes au lieu de simple qote
3- l'ajout de contrainte de type FK entre les tables contenant des libelles et la table de resources n'est pas possible, il n'y a pas de contraintes d'unicité sur la resourceKey (c'est normal, plusieurs suivant les nombres de langues)
On ne pourra pas garantir la présence de traduction, ce n'est pas gênant.

[35] ERROR:  there is no unique constraint matching given keys for referenced table "i18n_shared_nomenclature"
[35] STATEMENT:  /**
 	  * Génération de la contrainte de clef étrangère pour NO_DROIT.DRO_LIBELLE
 	 **/
 	alter table NO_DROIT
 		add constraint FK_NO_DROIT_DRO_LIBELLE foreign key (DRO_LIBELLE)
 			references I18N_SHARED_NOMENCLATURE (RESOURCE_KEY)
4- Proposition, la création de la table de libelle peut contenir une contrainte d'unicité sur les colonnes  (RESOURCE_KEY, LOCALE) sans que cela soit une PK 

create table I18N_EVALPA_LIBELLE (
     IEL_ID int8 generated by default as identity not null,
     RESOURCE_KEY varchar(255),
     LOCALE varchar(10),
     LABEL varchar(4000),
     constraint PK_IEL_ID primary key (IEL_ID),
     constraint UK_IEL_UNIQUE unique (RESOURCE_KEY, LOCALE)
);

**Comment by gideruette** [comment]
Traité sans le point 4
