### ISSUE TITLE
[Core] Templates de génération

### ISSUE THREAD

**Issue by kbuntrock** [klee-contrib/topmodel#360]
Il pourrait être sympathique d'ajouter des templates de génération de code à la manière de : https://github.com/klee-contrib/mda-code-generator/blob/master/mda-generator/src/main/resources/templates/createSQL_postgres.vm

Afin de soulager le travail de l'équipe TopModel pour des demandes telles que l'issue #359 359

**Comment by JabX** [comment]
Salut @kbuntrock,

L'architecture et la richesse fonctionnelle de TopModel est fondamentalement incompatible avec la mise en place de fichiers de templates génériques comme tu le proposes. Les différents besoins auxquels une telle solution pourrait réponse se répartissent dans plusieurs catégories : 
- Soit il s'agit de demandes comme celle de ton issue #359, qui sont des améliorations pures et dures du code généré, et qui donc devraient être poussées à tous les utilisateurs de TopModel. Si tu veux proposer ce genre de choses, on préfère largement que tu viennes nous faire une PR ici que tu gardes la modification dans ton coin.
- Soit il s'agit de petits ajustements spécifiques et localisés sur des propriétés, des classes ou des endpoints, qui se gèrent par des annotations à ajouter sur celles-ci. Pour répondre à ça, on a mis au point un système assez complet pour gérer ces annotations à tous les niveaux, et qui gère du templating sur à peu près toutes les propriétés imaginables du modèle.
- Soit il s'agit de quelque chose qui est fondamentalement différent de ce qu'on fait déjà, et dans ce cas tu as la possibilité d'écrire ton propre générateur et de l'intégrer à ta configuration TopModel pour qu'il soit utilisé. On a encore pas mal de boulot en attente pour simplifier ce travail (et en particulier pour pouvoir surcharger un générateur existant sans avoir à le forker), mais on y arrivera bien un jour.
