### ISSUE TITLE
 [Core] Pouvoir surcharger le nom d'une propriété d'association

### ISSUE THREAD

**Issue by kbuntrock** [klee-contrib/topmodel#374]
Il me semble que la capacité de nommer une association n'existe pas. On peut juste la suffixer via la propriété "role".

Exemple : 

![image](https://github.com/user-attachments/assets/dbffea6f-5346-46bf-a183-b519309afa8b)

Je souhaiterais idéalement ici que le nom de la variable soit "adresse" et non "siteAdresse".

**Comment by JabX** [comment]
(le problème ne se pose pas qu'en Java)
