### ISSUE TITLE
[JPA] Créer un mode FeignClient dans le générateur d'API client

### ISSUE THREAD

**Issue by rousselju** [klee-contrib/topmodel#419]
Nous souhaiterions ajouter des annotations sur les interfaces générées qui contiennent la définitions des endpoints d'un module.

(Le mécanisme des decorateurs correspondrait parfaitement au besoin avec la possibilité de gérer les imports associés et variabiliser les paramètres de l'annotation).

**Comment by gideruette** [comment]
Après discussions, il apparait plus pertinent dans un premier temps de créer un mode `FeignClient` dans le générateur d'API client.
