### ISSUE TITLE
Annoter les fichiers générés avec // <autogenerated />

### ISSUE THREAD

**Issue by sebez** [klee-contrib/topmodel#65]
## Contexte

Les analyseurs de code C# produisent des warnings.

## Constaté

Les fichiers générés par TopModel peuvent contenir des warnings qu'il n'est pas pertinent de corriger et qu'on ne peut pas corriger de manière pérenne puisque les corrections seront effacées par la prochaine regénération du modèle.

## Attendu

Annoter les fichiers générés en C# avec `// <autogenerated />` au début.

Cela permet de désactiver tous les warnings sur tous le fichier.

J'ai trouvé cette astuce sur [StackOverflow](https://stackoverflow.com/questions/70755097/how-to-ignore-specific-file-from-visual-studio-warnings-analyzer/70755376) mais je ne trouve pas de documentation officielle.

**Comment by JabX** [comment]
Les fichiers générés par TopModel ont vocation à ne pas déclencher de warnings intempestifs, donc cette annotation devrait être inutile. En l'occurrence, le warning ici était déclenché par une mauvaise configuration du générateur C# (si seulement il était documenté...).

Je ne suis pas fondamentalement contre le fait d'ajouter cette annotation, c'est juste que cela entrainerait une modification de tout le code généré jusqu'à présent pour rien. Si dans le futur une modification du générateur devrait impacter l'ensemble du code généré (de manière justifiée), alors on l'ajoutera à ce moment-là.
